export const ROUTE_PATHS = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  OAUTH2_CALLBACK: "/oauth2/callback",
  DASHBOARD: "/dashboard",
  MY_ACCOUNT: "/my-account",
  PAPERS: "/papers",
  TRENDS: "/trends",
  LIBRARY: "/library",
  NOTIFICATIONS: "/notifications",
  REPORTS: "/reports",
  ADMIN: "/admin",
};
